// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDREd82dZRUNYzBLkCGthoi9iQ14-hKB6Q',
    appId: '1:954947927646:web:50a81d1eeb04c141517ecf',
    messagingSenderId: '954947927646',
    projectId: 'mad-inclass-57ccf',
    authDomain: 'mad-inclass-57ccf.firebaseapp.com',
    storageBucket: 'mad-inclass-57ccf.firebasestorage.app',
    measurementId: 'G-0EMED4SBFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7TKfHe-RF8OBe4awcAOJRaLTSBt0NgPI',
    appId: '1:954947927646:android:db66e6790f6e07e4517ecf',
    messagingSenderId: '954947927646',
    projectId: 'mad-inclass-57ccf',
    storageBucket: 'mad-inclass-57ccf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_HDsNLzAMXq198-y_NC94YJ-pJCHeXRw',
    appId: '1:954947927646:ios:d778fb24c1e56396517ecf',
    messagingSenderId: '954947927646',
    projectId: 'mad-inclass-57ccf',
    storageBucket: 'mad-inclass-57ccf.firebasestorage.app',
    iosBundleId: 'com.example.inclass16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_HDsNLzAMXq198-y_NC94YJ-pJCHeXRw',
    appId: '1:954947927646:ios:d778fb24c1e56396517ecf',
    messagingSenderId: '954947927646',
    projectId: 'mad-inclass-57ccf',
    storageBucket: 'mad-inclass-57ccf.firebasestorage.app',
    iosBundleId: 'com.example.inclass16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDREd82dZRUNYzBLkCGthoi9iQ14-hKB6Q',
    appId: '1:954947927646:web:d771c52496e72d10517ecf',
    messagingSenderId: '954947927646',
    projectId: 'mad-inclass-57ccf',
    authDomain: 'mad-inclass-57ccf.firebaseapp.com',
    storageBucket: 'mad-inclass-57ccf.firebasestorage.app',
    measurementId: 'G-B66VKPF2YW',
  );
}
